"""
Generate subtitle files (.vtt) for all audio files in a given folder using OpenAI Whisper.

Usage:
    conda activate vibevoice
    python generate_subtitles.py <folder_path> [--language <lang>] [--model <model>]

Example:
    python generate_subtitles.py "E:/my_audio_files"
    python generate_subtitles.py "E:/my_audio_files" --language Chinese --model turbo
"""

import argparse
import glob
import os
import subprocess
import sys

# Audio file extensions supported by Whisper
AUDIO_EXTENSIONS = {
    ".mp3", ".wav", ".flac", ".ogg", ".m4a", ".wma",
    ".aac", ".opus", ".webm", ".mp4", ".avi", ".mkv",
}

# Subtitle extensions generated by Whisper (excluding .vtt which we want to keep)
SUBTITLE_EXTENSIONS_TO_REMOVE = {".srt", ".txt", ".tsv", ".json"}


def find_audio_files(folder: str) -> list[str]:
    """Find all audio files in the given folder (non-recursive)."""
    audio_files = []
    for entry in os.listdir(folder):
        filepath = os.path.join(folder, entry)
        if os.path.isfile(filepath):
            _, ext = os.path.splitext(entry)
            if ext.lower() in AUDIO_EXTENSIONS:
                audio_files.append(filepath)
    audio_files.sort()
    return audio_files


def run_whisper(audio_path: str, language: str, model: str) -> bool:
    """Run Whisper on a single audio file. Returns True on success."""
    filename = os.path.basename(audio_path)
    output_dir = os.path.dirname(audio_path)

    cmd = [
        "whisper",
        audio_path,
        "--model", model,
        "--language", language,
        "--output_dir", output_dir,
    ]

    print(f"\n{'='*60}")
    print(f"Processing: {filename}")
    print(f"Command:    {' '.join(cmd)}")
    print(f"{'='*60}")

    try:
        result = subprocess.run(cmd, check=True)
        print(f"✓ Successfully processed: {filename}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"✗ Failed to process: {filename} (exit code {e.returncode})")
        return False
    except FileNotFoundError:
        print("✗ Error: 'whisper' command not found.")
        print("  Make sure you have activated the correct conda environment:")
        print("  conda activate vibevoice")
        sys.exit(1)


def cleanup_non_vtt_files(folder: str, audio_files: list[str]):
    """Remove non-VTT subtitle files generated by Whisper, keeping only .vtt."""
    for audio_path in audio_files:
        base_name = os.path.splitext(os.path.basename(audio_path))[0]
        for ext in SUBTITLE_EXTENSIONS_TO_REMOVE:
            subtitle_file = os.path.join(folder, base_name + ext)
            if os.path.exists(subtitle_file):
                os.remove(subtitle_file)
                print(f"  Removed: {os.path.basename(subtitle_file)}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate .vtt subtitle files for all audio files in a folder using OpenAI Whisper."
    )
    parser.add_argument(
        "folder",
        help="Path to the folder containing audio files.",
    )
    parser.add_argument(
        "--language",
        default="English",
        help="Language of the audio (default: English).",
    )
    parser.add_argument(
        "--model",
        default="turbo",
        help="Whisper model to use (default: turbo).",
    )
    args = parser.parse_args()

    folder = os.path.abspath(args.folder)

    if not os.path.isdir(folder):
        print(f"Error: '{folder}' is not a valid directory.")
        sys.exit(1)

    # Find audio files
    audio_files = find_audio_files(folder)

    if not audio_files:
        print(f"No audio files found in: {folder}")
        print(f"Supported extensions: {', '.join(sorted(AUDIO_EXTENSIONS))}")
        sys.exit(0)

    print(f"Found {len(audio_files)} audio file(s) in: {folder}")
    for f in audio_files:
        print(f"  - {os.path.basename(f)}")

    # Process each audio file
    success_count = 0
    fail_count = 0

    for audio_path in audio_files:
        # Skip files that already have a .vtt subtitle
        base_name = os.path.splitext(os.path.basename(audio_path))[0]
        vtt_path = os.path.join(folder, base_name + ".vtt")
        if os.path.exists(vtt_path):
            print(f"\n⏭ Skipping (VTT already exists): {os.path.basename(audio_path)}")
            success_count += 1
            continue

        if run_whisper(audio_path, args.language, args.model):
            success_count += 1
        else:
            fail_count += 1

    # Clean up non-VTT subtitle files
    print(f"\n{'='*60}")
    print("Cleaning up non-VTT files...")
    cleanup_non_vtt_files(folder, audio_files)

    # Summary
    print(f"\n{'='*60}")
    print(f"Done! Processed {success_count + fail_count} file(s).")
    print(f"  ✓ Success: {success_count}")
    if fail_count:
        print(f"  ✗ Failed:  {fail_count}")
    print(f"VTT files saved in: {folder}")


if __name__ == "__main__":
    main()
